"""Generate the anonymised manuscript from paper.tex.

`paper_anon.tex` is GENERATED, never hand-edited. Maintaining two manuscripts
by hand is how the named and blinded versions drift, and a blinded version
that has silently fallen behind is worse than none -- it gets submitted.

What it does:
  1. replaces the author block with an anonymised one
  2. scans the result for identifying strings and REFUSES to write if any
     survive, so adding an acknowledgement or a repository URL to paper.tex
     later cannot leak into the blinded build unnoticed

The manuscript is a single self-contained .tex, so this emits a complete file
rather than a wrapper that \\input{}s the original.

Usage:  python3 make_anon.py [--check]
        --check verifies paper_anon.tex is current and clean, without writing.
Exit 1 if stale, or if anything identifying survives.
"""
from __future__ import annotations

import argparse
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "paper.tex")
OUT = os.path.join(HERE, "paper_anon.tex")

# Anything here must not appear in the generated file. Extend this list rather
# than trusting a future reader to remember; the check is the whole point.
FORBIDDEN = [
    "Sivaraman", "Mogana", "moganakumaran", "ieee.org",
    "San Francisco", "orcid", "ORCID",
    # the author's own artefact repository -- third-party GitHub URLs
    # (apache/atlas, odpi/egeria) are sources and must stay
    "github.com/moganakumaran", "operational-metadata-property-graph",
]

ANON_BLOCK = r"""%% Author block removed for anonymous review. This file is GENERATED by
%% make_anon.py from paper.tex -- edit that file, not this one.
\author{\IEEEauthorblockN{Author name withheld for review}
\IEEEauthorblockA{Affiliation withheld for review}}
"""

# Spliced span. The author block runs to \maketitle, which also takes out the
# \thanks footnote carrying the artefact URL -- that is deliberate: the URL
# names the author's GitHub account and is in FORBIDDEN below.
START, END = r"\author{", r"\maketitle"


def anonymise(tex: str) -> str:
    start = tex.index(START)
    end = tex.index(END)
    return tex[:start] + ANON_BLOCK + "\n" + tex[end:]


def leaks(tex: str) -> list[str]:
    return [t for t in FORBIDDEN if t.lower() in tex.lower()]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    src = open(SRC, encoding="utf-8").read()
    anon = anonymise(src)

    bad = leaks(anon)
    if bad:
        print("REFUSING: identifying strings survive anonymisation: "
              + ", ".join(bad))
        print("  Add the offending text to the author block, or extend "
              "FORBIDDEN and handle it here.")
        return 1

    if args.check:
        try:
            current = open(OUT, encoding="utf-8").read()
        except OSError:
            print("STALE: paper_anon.tex does not exist")
            return 1
        if current != anon:
            print("STALE: paper_anon.tex differs from paper.tex -- re-run")
            return 1
        print("paper_anon.tex is current and carries no identifying strings")
        return 0

    open(OUT, "w", encoding="utf-8").write(anon)
    print(f"wrote {os.path.basename(OUT)}")
    print(f"  scanned for {len(FORBIDDEN)} identifying patterns, none present")
    return 0


if __name__ == "__main__":
    sys.exit(main())
